#!/bin/bash
echo ""
echo "╔════════════════════════════════════════╗"
echo "║  ✨ Waypoint Development Environment  ║"
echo "╠════════════════════════════════════════╣"
echo "║  🖥️  Server  → http://localhost:8080  ║"
echo "║  💻 Client  → http://localhost:5173  ║"
echo "║  🗄️  Postgres → localhost:5432        ║"
echo "╚════════════════════════════════════════╝"
echo ""
